# Generated by Django 4.0.1 on 2022-01-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_arriesgado',
            field=models.BooleanField(default=False),
        ),
    ]
