# Generated by Django 4.0.1 on 2022-01-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('normal', 'Normal'), ('empresa', 'Empresa')], default='normal', max_length=30),
        ),
    ]
