# Generated by Django 4.0.1 on 2022-01-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cod_zip',
        ),
    ]
